# Yazi Keymap
# https://yazi-rs.github.io/docs/configuration/keymap

[manager]
keymap = [
    { on = [ "<Esc>" ], run = "escape", desc = "Exit visual mode, clear selected, or cancel search" },
    { on = [ "q" ],     run = "quit", desc = "Exit the process" },
    { on = [ "Q" ],     run = "quit --no-cwd-file", desc = "Exit the process without writing cwd-file" },
    { on = [ "<C-q>" ], run = "close", desc = "Close the current tab, or quit if it is the last tab" },
    { on = [ "<C-z>" ], run = "suspend", desc = "Suspend the process" },

    # Navigation
    { on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
    { on = [ "j" ], run = "arrow 1",  desc = "Move cursor down" },
    { on = [ "K" ], run = "arrow -5", desc = "Move cursor up 5 lines" },
    { on = [ "J" ], run = "arrow 5",  desc = "Move cursor down 5 lines" },
    { on = [ "<Up>" ],   run = "arrow -1", desc = "Move cursor up" },
    { on = [ "<Down>" ], run = "arrow 1",  desc = "Move cursor down" },
    { on = [ "<Left>" ],  run = "leave", desc = "Go back to the parent directory" },
    { on = [ "<Right>" ], run = "enter", desc = "Enter the child directory" },
    { on = [ "h" ], run = "leave", desc = "Go back to the parent directory" },
    { on = [ "l" ], run = "enter", desc = "Enter the child directory" },
    { on = [ "H" ], run = "back",    desc = "Go back to the previous directory" },
    { on = [ "L" ], run = "forward", desc = "Go forward to the next directory" },

    # Selection
    { on = [ "<Space>" ], run = [ "select --state=none", "arrow 1" ], desc = "Toggle the current selection state" },
    { on = [ "v" ],       run = "visual_mode",                        desc = "Enter visual mode (selection mode)" },
    { on = [ "V" ],       run = "visual_mode --unset",                desc = "Enter visual mode (unset mode)" },
    { on = [ "<C-a>" ],   run = "select_all --state=true",            desc = "Select all files" },
    { on = [ "<C-r>" ],   run = "select_all --state=none",            desc = "Inverse selection of all files" },

    # Operation
    { on = [ "o" ],         run = "open",                        desc = "Open the selected files" },
    { on = [ "O" ],         run = "open --interactive",          desc = "Open the selected files interactively" },
    { on = [ "<Enter>" ],   run = "open",                        desc = "Open the selected files" },
    { on = [ "<C-Enter>" ], run = "open --interactive",          desc = "Open the selected files interactively" },
    { on = [ "y" ],         run = "yank",                        desc = "Copy the selected files" },
    { on = [ "x" ],         run = "yank --cut",                  desc = "Cut the selected files" },
    { on = [ "p" ],         run = "paste",                       desc = "Paste the files" },
    { on = [ "P" ],         run = "paste --force",               desc = "Paste the files (overwrite if the destination exists)" },
    { on = [ "-" ],         run = "link",                        desc = "Symlink the absolute path of files" },
    { on = [ "_" ],         run = "link --relative",             desc = "Symlink the relative path of files" },
    { on = [ "d" ],         run = "remove",                      desc = "Move the files to the trash" },
    { on = [ "D" ],         run = "remove --permanently",        desc = "Permanently delete the files" },
    { on = [ "a" ],         run = "create",                      desc = "Create a file or directory (ends with / for directory)" },
    { on = [ "r" ],         run = "rename --cursor=before_ext",  desc = "Rename a file or directory" },
    { on = [ ";" ],         run = "shell",                       desc = "Run a shell command" },
    { on = [ ":" ],         run = "shell --block",               desc = "Run a shell command (block the UI)" },
    { on = [ "." ],         run = "hidden toggle",               desc = "Toggle the visibility of hidden files" },
    { on = [ "s" ],         run = "search fd",                   desc = "Search files by name using fd" },
    { on = [ "S" ],         run = "search rg",                   desc = "Search files by content using ripgrep" },
    { on = [ "<C-s>" ],     run = "search none",                 desc = "Cancel the ongoing search" },
    { on = [ "z" ],         run = "plugin zoxide",               desc = "Jump to a directory using zoxide" },
    { on = [ "Z" ],         run = "plugin fzf",                  desc = "Jump to a directory, or reveal a file using fzf" },

    # Tabs
    { on = [ "t" ], run = "tab_create --current", desc = "Create a new tab using the current path" },
    { on = [ "1" ], run = "tab_switch 0", desc = "Switch to the first tab" },
    { on = [ "2" ], run = "tab_switch 1", desc = "Switch to the second tab" },
    { on = [ "3" ], run = "tab_switch 2", desc = "Switch to the third tab" },
    { on = [ "4" ], run = "tab_switch 3", desc = "Switch to the fourth tab" },
    { on = [ "5" ], run = "tab_switch 4", desc = "Switch to the fifth tab" },
    { on = [ "6" ], run = "tab_switch 5", desc = "Switch to the sixth tab" },
    { on = [ "7" ], run = "tab_switch 6", desc = "Switch to the seventh tab" },
    { on = [ "8" ], run = "tab_switch 7", desc = "Switch to the eighth tab" },
    { on = [ "9" ], run = "tab_switch 8", desc = "Switch to the ninth tab" },
    { on = [ "[" ], run = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
    { on = [ "]" ], run = "tab_switch 1 --relative",  desc = "Switch to the next tab" },
    { on = [ "{" ], run = "tab_swap -1", desc = "Swap the current tab with the previous tab" },
    { on = [ "}" ], run = "tab_swap 1",  desc = "Swap the current tab with the next tab" },

    # Tasks
    { on = [ "w" ], run = "tasks_show", desc = "Show the tasks manager" },

    # Help
    { on = [ "~" ], run = "help", desc = "Open the help" },
]
